### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Dreamersoul** [yehia2amer/Dell-Precision-T7610-Workstation-Hackintosh-Guide#1]
thanks for putting this together i have the same machine the only difference is that i have Nvidia quatro K5000. i have copied your clover folder into mine the issue is when i start the installation the screen goes black and says no signal any idea?
im installing OSX 10.14.0

**Comment by cstrouse** [comment]
Try removing `nv_disable=1` and adding `nvda_drv=1`. I have a T3610 with a K2000 and got it working that way with 10.15.
